version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test
      - run:
        command: cobertura:cobertura # checkout, build, test, and upload test results
      - run:
        command: bash <(curl -s https://codecov.io/bash)